### ISSUE TITLE
Simulate the SIR or SEIR model on SimInf

### ISSUE THREAD

**Issue by Spatial-R** [stewid/SimInf#1]
Thanks for your development of the **SimInf** package, which provides several types of dynamic models such as SIS. In my situation, there is no transition from the Infectious compartment to the Susceptible compartment, there i need to modify the model setting in the package. My idea is:
- firstly, set the transition rate from the Infectious compartment zero;
- secondly, add the rate (transition from the Infectious compartment to Recovery compartment) to the **exit rate**.  

But that way will influence the total number of population in all nodes. Is there any other ways can help to build the SIR model  using SimInf?

**Comment by stewid** [comment]
The latest version (v3.0.0) of SimInf on CRAN includes the SEIR and
SIR models.

```{r}
library("SimInf")

## Create an SIR model object.
model <- SIR(u0 = data.frame(S = 99, I = 1, R = 0),
             tspan = 1:100,
             beta = 0.16,
             gamma = 0.077)

## Run the SIR model and plot the result.
result <- run(model, seed = 123)
plot(result)
```
![sir](https://cloud.githubusercontent.com/assets/1815965/23077153/a1b68ae2-f543-11e6-9fad-ba601623db49.png)

```{r}
## Create an SEIR model object.
model <- SEIR(u0 = data.frame(S = 99, E = 0, I = 1, R = 0),
              tspan = 1:100,
              beta = 0.16,
              epsilon = 0.25,
              gamma = 0.077)

## Run the SEIR model and plot the result.
result <- run(model, seed = 123)
plot(result)
```
![seir](https://cloud.githubusercontent.com/assets/1815965/23077168/b0bf60e0-f543-11e6-8eb2-39afb4409743.png)

**Comment by trosendal** [comment]
Nice graphs!
