### ISSUE TITLE
trajectory method - variable names

### ISSUE THREAD

**Issue by trosendal** [stewid/SimInf#12]
I'm playing with the trajectory method and wonder why you chose the name 'Node' for that item in the dataframe? I notice if I want the sparse variant I can submit a similar df to the U before running the model so that makes sense but the u0 object has the column name 'ID' doesn't it? Shouldn't these be the same?

**Comment by stewid** [comment]
@trosendal, thanks for the question.

The `id` column was removed from u0 in version 2.0, see e.g. the example dataset `u0_SISe3`. However, I realize I should rename 'Node' to 'node', and `Time` to `time` for consistency with scheduled events data, see e.g. `events_SISe3`.

**Comment by stewid** [comment]
I have renamed `Node` to `node` and `Time` to `time`.
