### ISSUE TITLE
Loading the Confidence Interval for the Result

### ISSUE THREAD

**Issue by yijunwang0805** [stewid/SimInf#32]
Hi, 

Thank you for your great package! It makes my life easier!

It is me again. I used another laptop to install the package and it turns out to be successful.

I ran a model, which ran successfully. 

I would like to draw a graph without drawing the susceptible variable. So I tried ggplot by extracting values from `Result`.

However, when I tried to view the result. It showed an error.

```r
View(result)
Error in if (more || nchar(output) > 80) { : 
  missing value where TRUE/FALSE needed
```

Could you please help take a look?

**Comment by yijunwang0805** [comment]
After reading `SimInf` manual,

I found a solution built by the author.

Use `trajectory` to extract result.
`trajectory(result)`

Bravo! Problem solved.

**Comment by yijunwang0805** [comment]
How do I load the confidence interval for the result?

**Comment by stewid** [comment]
Great to hear that you found a solution.
