### ISSUE TITLE
SimInf Error

### ISSUE THREAD

**Issue by JNAKATO** [stewid/SimInf#37]
Error: "C:/rtools40/mingw64/bin/"gcc  -I"C:/R/R/R-41~1.0/include" -DNDEBUG -I"C:/R/R/R-4.1.0/library/SimInf/include" -DSIMINF_MODEL_RUN=run_249c247652b7 -DSIMINF_R_INIT=R_init_SimInf_249c247652b7 -DSIMINF_FORCE_SYMBOLS=FALSE         -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c C:/Users/HP840G~1/AppData/Local/Temp/RtmpGi9NPi/SimInf_249c247652b7.c -o C:/Users/HP840G~1/AppData/Local/Temp/RtmpGi9NPi/SimInf_249c247652b7.osh: line 6: tmp.def: No such file or directorysh: line 7: tmp.def: No such file or directoryC:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o C:/Users/HP840G~1/AppData/Local/Temp/RtmpGi9NPi/SimInf_249c247652b7.dll tmp.def C:/Users/HP840G~1/AppData/Local/Temp/RtmpGi9NPi/SimInf_249c247652b7.o -LC:/R/R/R-41~1.0/bin/x64 -lRgcc.exe: error: tmp.def: No such file or directory ###I HAVE FAILED TO GET THIS PACKAGE UP AND RUNNING. THAT IS THE ERROR AM CONTINUOUSLY GETTING

**Comment by stewid** [comment]
Hi @JNAKATO Could you please provide an example off the code you are running to get the error?

**Comment by JNAKATO** [comment]
install.packages('SimInf')
library(SimInf)
###specify variables
N<-500
I0<-1
B<-0.5
tspan<-seq(from=1,t=30,by= 1)

####Commands for performing the simulations
parms<- c(beta=B)
initial_state<-data.frame(S=N-I0,I=I0)
compartments<- c('S','I')
transitions<- c('S -> beta*S*I/(S+I) -> I')
getwd()

model<- mparse(transitions = transitions,compartments = compartments,gdata = parms,u0 = initial_state,tspan = tspan)
out<-run(model = model ,threads = 1)
plot(out)

**Comment by trosendal** [comment]
@JNAKATO Hi! Your C code in the transitions seems to be invalid. I guess you want to multiply the S and I compartments with the beta parameter? like this:

    transitions<- c('S -> beta*S*I/(S+I) -> I')

That should work

**Comment by JNAKATO** [comment]
I still get the same error. I was only able to run the model using another computer

**Comment by stewid** [comment]
@JNAKATO Does it work if you put Rtools on the path using the instructions from https://cran.r-project.org/bin/windows/Rtools/ and run the following in R
```
writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")
```
and then restart R?

**Comment by JNAKATO** [comment]
I have tried that several times . I also reinstalled by R and Rtools but i was still getting the same error

**Comment by stewid** [comment]
I will close this issue since I think it is related to configuring Rtools and not directly an issue with SimInf. However, do not hesitate to re-open the issue if you you have more information or if there is anything in SimInf that can be changed to fix this.

**Comment by JNAKATO** [comment]
Its alright. Thank you
________________________________
