### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by MAAJ21** [stewid/SimInf#38]
Hi, 
My group and I are doing a project on hotspot prediction for Covid-19 and were recommended to use your package by Robin Eriksson. However, when trying to install a specific branch through Rstudio we get an error. When installing the master branch we get no errors, however when trying to install the pmcmc or the particle-filter branches we get the error below.

`ERROR: package installation failed
Error: Failed to install 'SimInf' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> "C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.2/include" -DNDEBUG -I../windows/gsl-2.7/include -I. -I../inst/include -DR_NO_REMAP -DSTRICT_R_HEADERS      -fopenmp   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -fdiagnostics-color=always -c models/SISe.c -o models/SISe.o
E> C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o SimInf.dll SimInf-win.def init.o SimInf.o solvers/SimInf_solver.o solvers/aem/SimInf_solver_aem.o solvers/ssm/SimInf_solver_ssm.o misc/SimInf_abc.o misc/SimInf_arg.o misc/SimInf_forward_euler_linear_decay.o misc/SimInf_ldata.o misc/SimInf_local_spread.o misc/SimInf_openmp.o misc/SimInf_trajectory.o misc/binheap.o models/SISe3_sp.o models/SISe3.o models/SEIR.o models/SISe_sp.o models/SIR.o models/SISe.o -L../windows/gsl-2.7/lib/x64 -lm -lgsl -lgslcblas -fopenmp -LC:/PROGRA~1/R/R-41~1.2/bin/x6`

We are unsure if this is because we are doing something wrong or if this is due to the package being under development. If we are doing something wrong would you be able to help us install either the pmcmc or the particle-filter branch. We are using windows laptops and we have installed rtools correctly (hopefully). We have also ubuntu as windows subsystems.

Thank you in advance
Aikaterini

**Comment by stewid** [comment]
Thanks for reporting the issue. I've now updated the build-configuration on Windows which was missing a file. Could you please try to install again - hopefully it works now.

Kind regards
Stefan

**Comment by MAAJ21** [comment]
It seems to work now, thank you!

**Comment by stewid** [comment]
Thanks for reporting back.
